[providers]
nodejs = "20"

[variables]
NPM_CONFIG_PRODUCTION = "false"
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = ["npm ci --verbose"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"